on:
  workflow_dispatch:
jobs:
  deploy_job:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ env.CD_HOST }}
        port: ${{ env.CD_PORT }}
        username: ${{ env.CD_USERNAME }}
        key: ${{ secrets.CD_KEY }}
        script_stop: true
        debug: true
        script: |
          cd ~/order_bot
          git reset --hard
          git pull
          pm2 reload order_bot
        
    
